asyncapi: 2.6.0
info:
  title: A4C Domain Events
  version: 1.0.0
  description: |
    Event-driven architecture specification for Analytics4Change platform.
    All events capture WHO, WHAT, WHEN, and most importantly WHY changes occur.
  contact:
    name: A4C Development Team
  license:
    name: Private

servers:
  development:
    url: postgresql://localhost:54322/postgres
    protocol: postgresql
    description: Local Supabase development instance
  production:
    url: postgresql://{project-ref}.supabase.co:5432/postgres
    protocol: postgresql
    description: Production Supabase instance
    variables:
      project-ref:
        default: tmrjlswbsxmbglmaclxu
        description: Supabase project reference

defaultContentType: application/json

channels:
  domain_events:
    description: Main event stream for all domain events
    publish:
      summary: Publish domain events to the system
      operationId: publishDomainEvent
      message:
        oneOf:
          # NOTE: client.yaml and medication.yaml domains removed (2025-01-10)
          # Legacy CRUD tables dropped - will be redefined with proper event-driven architecture
          - $ref: './domains/user.yaml#/components/messages/UserSyncedFromAuth'
          - $ref: './domains/user.yaml#/components/messages/UserOrganizationSwitched'
          - $ref: './domains/user.yaml#/components/messages/UserDeactivated'
          - $ref: './domains/user.yaml#/components/messages/UserReactivated'
          - $ref: './domains/user.yaml#/components/messages/UserDeleted'
          - $ref: './domains/invitation.yaml#/components/messages/UserInvited'
          - $ref: './domains/invitation.yaml#/components/messages/InvitationRevoked'
          - $ref: './domains/invitation.yaml#/components/messages/InvitationAccepted'
          - $ref: './domains/invitation.yaml#/components/messages/InvitationExpired'
          - $ref: './domains/invitation.yaml#/components/messages/InvitationResent'
          - $ref: './domains/invitation.yaml#/components/messages/InvitationEmailSent'
          # Organization lifecycle events
          - $ref: './domains/organization.yaml#/components/messages/OrganizationCreated'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationUpdated'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationActivated'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationDeactivated'
          # Organization DNS events (subdomain provisioning)
          - $ref: './domains/organization.yaml#/components/messages/OrganizationSubdomainDnsCreated'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationSubdomainVerified'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationDnsRemoved'
          # Organization bootstrap events
          - $ref: './domains/organization.yaml#/components/messages/OrganizationBootstrapInitiated'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationBootstrapCompleted'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationBootstrapFailed'
          - $ref: './domains/organization.yaml#/components/messages/OrganizationBootstrapCancelled'
          - $ref: './domains/program.yaml#/components/messages/ProgramCreated'
          # Organization Unit events (sub-organizations within provider hierarchy)
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitCreated'
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitUpdated'
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitDeactivated'
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitReactivated'
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitDeleted'
          - $ref: './domains/organization-unit.yaml#/components/messages/OrganizationUnitMoved'
          # Platform Admin audit events (observability and system management)
          - $ref: './domains/platform-admin.yaml#/components/messages/PlatformAdminFailedEventsViewed'
          - $ref: './domains/platform-admin.yaml#/components/messages/PlatformAdminEventRetryAttempted'
          - $ref: './domains/platform-admin.yaml#/components/messages/PlatformAdminProcessingStatsViewed'
          - $ref: './domains/platform-admin.yaml#/components/messages/PlatformAdminEventDismissed'
          - $ref: './domains/platform-admin.yaml#/components/messages/PlatformAdminEventUndismissed'
          # Email entity events
          - $ref: './domains/email.yaml#/components/messages/EmailCreated'
          - $ref: './domains/email.yaml#/components/messages/EmailUpdated'
          - $ref: './domains/email.yaml#/components/messages/EmailDeleted'
          # Contact entity events
          - $ref: './domains/contact.yaml#/components/messages/ContactCreated'
          - $ref: './domains/contact.yaml#/components/messages/ContactUpdated'
          - $ref: './domains/contact.yaml#/components/messages/ContactDeleted'
          # Phone entity events
          - $ref: './domains/phone.yaml#/components/messages/PhoneCreated'
          - $ref: './domains/phone.yaml#/components/messages/PhoneUpdated'
          - $ref: './domains/phone.yaml#/components/messages/PhoneDeleted'
          # Address entity events
          - $ref: './domains/address.yaml#/components/messages/AddressCreated'
          - $ref: './domains/address.yaml#/components/messages/AddressUpdated'
          - $ref: './domains/address.yaml#/components/messages/AddressDeleted'
          # Junction events (organization-entity relationships)
          - $ref: './domains/junction.yaml#/components/messages/OrganizationContactLinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationContactUnlinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationAddressLinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationAddressUnlinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationPhoneLinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationPhoneUnlinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationEmailLinked'
          - $ref: './domains/junction.yaml#/components/messages/OrganizationEmailUnlinked'
          # Junction events (contact-entity relationships)
          - $ref: './domains/junction.yaml#/components/messages/ContactPhoneLinked'
          - $ref: './domains/junction.yaml#/components/messages/ContactPhoneUnlinked'
          - $ref: './domains/junction.yaml#/components/messages/ContactAddressLinked'
          - $ref: './domains/junction.yaml#/components/messages/ContactAddressUnlinked'
          - $ref: './domains/junction.yaml#/components/messages/ContactEmailLinked'
          - $ref: './domains/junction.yaml#/components/messages/ContactEmailUnlinked'
          # Junction events (phone-address relationship)
          - $ref: './domains/junction.yaml#/components/messages/PhoneAddressLinked'
          - $ref: './domains/junction.yaml#/components/messages/PhoneAddressUnlinked'
          # RBAC events (roles and permissions)
          - $ref: './domains/rbac.yaml#/components/messages/PermissionDefined'
          - $ref: './domains/rbac.yaml#/components/messages/RoleCreated'
          - $ref: './domains/rbac.yaml#/components/messages/RolePermissionGranted'
          - $ref: './domains/rbac.yaml#/components/messages/RolePermissionRevoked'
          - $ref: './domains/rbac.yaml#/components/messages/RoleUpdated'
          - $ref: './domains/rbac.yaml#/components/messages/RoleDeactivated'
          - $ref: './domains/rbac.yaml#/components/messages/RoleReactivated'
          - $ref: './domains/rbac.yaml#/components/messages/RoleDeleted'
          - $ref: './domains/rbac.yaml#/components/messages/UserRoleAssigned'
          - $ref: './domains/rbac.yaml#/components/messages/UserRoleRevoked'
          - $ref: './domains/rbac.yaml#/components/messages/AccessGrantCreated'
          - $ref: './domains/rbac.yaml#/components/messages/AccessGrantRevoked'
    subscribe:
      summary: Subscribe to domain events
      operationId: onDomainEvent
      message:
        $ref: '#/channels/domain_events/publish/message'

components:
  schemas:
    DomainEvent:
      type: object
      required:
        - id
        - stream_id
        - stream_type
        - stream_version
        - event_type
        - event_data
        - event_metadata
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique event identifier
        stream_id:
          type: string
          format: uuid
          description: The entity/aggregate this event belongs to
        stream_type:
          type: string
          enum:
            # NOTE: client, medication, medication_history, dosage removed (2025-01-10)
            # Legacy CRUD tables dropped - will be redefined with proper event-driven architecture
            - user
            - organization
            - organization_unit
            - invitation
            - program
            - platform_admin
            - impersonation
            - role
            - permission
            - contact
            - address
            - phone
            - email
            - access_grant
            - junction
          description: Type of entity this event affects
        stream_version:
          type: integer
          minimum: 1
          description: Version number within this stream
        event_type:
          type: string
          pattern: '^[a-z_]+\.[a-z_]+$'
          description: Event type in format domain.action
          examples:
            - user.synced_from_auth
            - organization.bootstrap_initiated
        event_data:
          type: object
          description: The actual event payload
        event_metadata:
          $ref: './components/schemas.yaml#/components/schemas/EventMetadata'
        created_at:
          type: string
          format: date-time
          description: When the event was created
        processed_at:
          type: string
          format: date-time
          description: When the event was successfully processed
          nullable: true
        processing_error:
          type: string
          description: Error message if processing failed
          nullable: true