export { IntakeFormField } from './IntakeFormField';
export { getFieldProps } from './useFieldProps';
export { DemographicsSection } from './DemographicsSection';
export { ContactInfoSection } from './ContactInfoSection';
export { GuardianSection } from './GuardianSection';
export { ReferralSection } from './ReferralSection';
export { AdmissionSection } from './AdmissionSection';
export { InsuranceSection } from './InsuranceSection';
export { ClinicalSection } from './ClinicalSection';
export { MedicalSection } from './MedicalSection';
export { LegalSection } from './LegalSection';
export { EducationSection } from './EducationSection';
export type { IntakeSectionProps } from './types';
