/**
 * Shared Types and Interfaces
 *
 * Central TypeScript type definitions for workflows and activities.
 * All types are exported from this single file for easy imports.
 */

// ========================================
// Workflow Types
// ========================================

/**
 * DNS Retry Configuration
 */
export interface DnsRetryConfig {
  /** Base delay in milliseconds for exponential backoff (default: 10000) */
  baseDelayMs?: number;
  /** Maximum delay cap in milliseconds (default: 300000) */
  maxDelayMs?: number;
  /** Maximum retry attempts (default: 7) */
  maxAttempts?: number;
}

/**
 * Contact information for organization (legacy - use BootstrapContactInput for new code)
 * @deprecated Use BootstrapContactInput from generated events
 */
export interface ContactInfo {
  firstName: string;
  lastName: string;
  email: string;
  title?: string;
  department?: string;
  type: 'a4c_admin' | 'billing' | 'technical' | 'emergency' | 'stakeholder';
  label: string;
}

/**
 * Address information for organization (legacy - use BootstrapAddressInput for new code)
 * @deprecated Use BootstrapAddressInput from generated events
 */
export interface AddressInfo {
  street1: string;
  street2?: string;
  city: string;
  state: string;
  zipCode: string;
  type: 'physical' | 'mailing' | 'billing';
  label: string;
}

/**
 * Phone information for organization (legacy - use BootstrapPhoneInput for new code)
 * @deprecated Use BootstrapPhoneInput from generated events
 */
export interface PhoneInfo {
  number: string;
  extension?: string;
  type: 'mobile' | 'office' | 'fax' | 'emergency';
  label: string;
}

/**
 * Email information for organization (legacy - use BootstrapEmailInput for new code)
 * @deprecated Use BootstrapEmailInput from generated events
 */
export interface EmailInfo {
  address: string;
  type: 'work' | 'personal' | 'billing' | 'support' | 'main';
  label: string;
}

/**
 * Input parameters for OrganizationBootstrapWorkflow
 */
export interface OrganizationBootstrapParams {
  /** Organization ID - pre-generated by the API and used as stream_id for all events */
  organizationId: string;

  /** Subdomain for the organization (optional - required for providers and VAR partners only) */
  subdomain?: string;

  /** Organization details */
  orgData: {
    name: string;
    type: 'provider' | 'provider_partner' | 'platform_owner';
    parentOrgId?: string;  // Required for partners, optional for providers

    /** Contact information (at least one contact required across all sections) */
    contacts: ContactInfo[];

    /** Address information (required) */
    addresses: AddressInfo[];

    /** Phone information (required) */
    phones: PhoneInfo[];

    /** Partner type (required when type='partner') */
    partnerType?: 'var' | 'family' | 'court' | 'other';

    /** Referring partner organization ID (optional) */
    referringPartnerId?: string;
  };

  /** Users to invite */
  users: Array<{
    email: string;
    firstName: string;
    lastName: string;
    role: string;
  }>;

  /**
   * Frontend URL for invitation links.
   * Optional - if not provided, activity will use FRONTEND_URL from env config.
   */
  frontendUrl?: string;

  /**
   * Optional DNS retry configuration (for testing)
   * Defaults to production values if not specified
   */
  retryConfig?: DnsRetryConfig;

  /**
   * Optional tracing context for end-to-end request correlation
   * Propagated from Edge Functions to enable debugging across services
   */
  tracing?: WorkflowTracingParams;
}

/**
 * Result returned from OrganizationBootstrapWorkflow
 */
export interface OrganizationBootstrapResult {
  /** Created organization ID */
  orgId: string;

  /** Full domain name */
  domain: string;

  /** Whether DNS was configured successfully */
  dnsConfigured: boolean;

  /** Number of invitations sent successfully */
  invitationsSent: number;

  /** Any errors that occurred (non-fatal) */
  errors?: string[];
}

/**
 * Internal workflow state tracking
 */
export interface WorkflowState {
  /** Organization ID (set after creation) */
  orgId?: string;

  /** Full domain name (set after DNS configuration) */
  domain?: string;

  /** DNS record ID from Cloudflare (set after DNS configuration) */
  dnsRecordId?: string;

  /** Generated invitations (set after generation) */
  invitations?: Invitation[];

  /** Whether organization was created */
  orgCreated: boolean;

  /** Whether DNS was configured */
  dnsConfigured: boolean;

  /** Whether DNS was skipped (no subdomain required) */
  dnsSkipped: boolean;

  /** Whether invitations were sent */
  invitationsSent: boolean;

  /** Non-fatal errors */
  errors: string[];

  /** Errors during compensation (rollback) */
  compensationErrors: string[];
}

// ========================================
// Activity Types
// ========================================

/**
 * CreateOrganizationActivity parameters
 *
 * Supports two input modes:
 * 1. Legacy mode: contacts/phones/addresses arrays with simple types (deprecated)
 * 2. Bootstrap mode: bootstrapContacts/bootstrapPhones/bootstrapEmails/bootstrapAddresses
 *    arrays with temp_id and contact_ref for correlation
 *
 * When bootstrap arrays are provided, they take precedence over legacy arrays.
 */
export interface CreateOrganizationParams {
  /** Organization ID - pre-generated by the API, used as stream_id for all events */
  organizationId: string;
  name: string;
  type: 'provider' | 'provider_partner' | 'platform_owner';
  parentOrgId?: string;
  subdomain?: string;

  /** @deprecated Use bootstrapContacts with temp_id correlation */
  contacts: ContactInfo[];
  /** @deprecated Use bootstrapAddresses with temp_id/contact_ref correlation */
  addresses: AddressInfo[];
  /** @deprecated Use bootstrapPhones with temp_id/contact_ref correlation */
  phones: PhoneInfo[];
  /** @deprecated Use bootstrapEmails with temp_id/contact_ref correlation */
  emails?: EmailInfo[];

  /**
   * Bootstrap contacts with temp_id for correlation.
   * When provided, takes precedence over legacy `contacts` array.
   * Each contact's temp_id is used to resolve contact_ref in phones/emails/addresses.
   */
  bootstrapContacts?: import('./generated/events.js').BootstrapContactInput[];

  /**
   * Bootstrap phones with temp_id and optional contact_ref.
   * When provided, takes precedence over legacy `phones` array.
   * contact_ref links to a contact's temp_id for contact↔phone junction.
   */
  bootstrapPhones?: import('./generated/events.js').BootstrapPhoneInput[];

  /**
   * Bootstrap emails with temp_id and optional contact_ref.
   * contact_ref links to a contact's temp_id for contact↔email junction.
   */
  bootstrapEmails?: import('./generated/events.js').BootstrapEmailInput[];

  /**
   * Bootstrap addresses with temp_id and optional contact_ref.
   * When provided, takes precedence over legacy `addresses` array.
   * contact_ref links to a contact's temp_id for contact↔address junction.
   */
  bootstrapAddresses?: import('./generated/events.js').BootstrapAddressInput[];

  partnerType?: 'var' | 'family' | 'court' | 'other';
  referringPartnerId?: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * ConfigureDNSActivity parameters
 */
export interface ConfigureDNSParams {
  orgId: string;
  subdomain: string;
  /** Target domain for CNAME. Defaults to PLATFORM_BASE_DOMAIN from env config. */
  targetDomain?: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * ConfigureDNSActivity result
 */
export interface ConfigureDNSResult {
  /** Full qualified domain name */
  fqdn: string;

  /** DNS record ID from provider (for cleanup) */
  recordId: string;
}

/**
 * VerifyDNSActivity parameters
 */
export interface VerifyDNSParams {
  orgId: string;
  domain: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * GenerateInvitationsActivity parameters
 */
export interface GenerateInvitationsParams {
  orgId: string;
  users: Array<{
    email: string;
    firstName: string;
    lastName: string;
    role: string;
  }>;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * Invitation object
 */
export interface Invitation {
  invitationId: string;
  email: string;
  token: string;
  expiresAt: Date;
}

/**
 * SendInvitationEmailsActivity parameters
 */
export interface SendInvitationEmailsParams {
  orgId: string;
  invitations: Invitation[];
  domain: string;
  /** Frontend URL for invitation links. Defaults to FRONTEND_URL from env config. */
  frontendUrl?: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * SendInvitationEmailsActivity result
 */
export interface SendInvitationEmailsResult {
  successCount: number;
  failures: Array<{
    email: string;
    error: string;
  }>;
}

/**
 * ActivateOrganizationActivity parameters
 */
export interface ActivateOrganizationParams {
  orgId: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

// ========================================
// Compensation Activity Types
// ========================================

/**
 * RemoveDNSActivity parameters (compensation)
 */
export interface RemoveDNSParams {
  orgId: string;
  subdomain: string;
}

/**
 * DeactivateOrganizationActivity parameters (compensation)
 */
export interface DeactivateOrganizationParams {
  orgId: string;
}

/**
 * RevokeInvitationsActivity parameters (compensation)
 */
export interface RevokeInvitationsParams {
  orgId: string;
}

/**
 * DeleteContactsActivity parameters (compensation)
 */
export interface DeleteContactsParams {
  orgId: string;
}

/**
 * DeleteAddressesActivity parameters (compensation)
 */
export interface DeleteAddressesParams {
  orgId: string;
}

/**
 * DeletePhonesActivity parameters (compensation)
 */
export interface DeletePhonesParams {
  orgId: string;
}

/**
 * DeleteEmailsActivity parameters (compensation)
 */
export interface DeleteEmailsParams {
  orgId: string;
}

/**
 * GrantProviderAdminPermissionsActivity parameters
 */
export interface GrantProviderAdminPermissionsParams {
  /** Organization ID */
  orgId: string;
  /** Scope path for the role (e.g., subdomain like 'acme-health') */
  scopePath: string;
  /** Optional tracing context for end-to-end request correlation */
  tracing?: WorkflowTracingParams;
}

/**
 * GrantProviderAdminPermissionsActivity result
 */
export interface GrantProviderAdminPermissionsResult {
  /** Role ID (UUID) */
  roleId: string;
  /** Number of permissions granted (0 if all already existed) */
  permissionsGranted: number;
  /** Whether role already existed */
  roleAlreadyExisted: boolean;
}

// ========================================
// Provider Interface Types
// ========================================

/**
 * DNS Zone information
 */
export interface DNSZone {
  id: string;
  name: string;
}

/**
 * DNS Record information
 */
export interface DNSRecord {
  id: string;
  type: string;
  name: string;
  content: string;
  ttl?: number;
  proxied?: boolean;
}

/**
 * DNS Record filter
 */
export interface DNSRecordFilter {
  name?: string;
  type?: string;
}

/**
 * Parameters for creating a DNS record
 */
export interface CreateDNSRecordParams {
  type: string;
  name: string;
  content: string;
  ttl?: number;
  proxied?: boolean;
}

/**
 * Email parameters
 */
export interface EmailParams {
  from: string;
  to: string;
  subject: string;
  html: string;
  text?: string;
}

/**
 * Email send result
 */
export interface EmailResult {
  messageId: string;
  accepted: string[];
  rejected: string[];
}

// ========================================
// Tracing Types
// ========================================

/**
 * Tracing Context for end-to-end request correlation
 *
 * Propagated from frontend → Edge Functions → Temporal → Activities
 * Enables debugging failed requests by correlation ID and session attribution.
 *
 * W3C Trace Context compatible:
 * - trace_id: 32 hex chars (UUID without dashes)
 * - span_id: 16 hex chars
 * - parent_span_id: Links to parent operation
 */
export interface TracingContext {
  /** Business request correlation ID (UUID) - groups related operations */
  correlationId: string;

  /** User auth session ID from Supabase JWT (null if unauthenticated) */
  sessionId: string | null;

  /** W3C compatible trace ID (32 hex chars) - spans entire request lifecycle */
  traceId: string;

  /** Current span ID (16 hex chars) - identifies this specific operation */
  spanId: string;

  /** Parent span ID (16 hex chars) - links to parent operation for causation chain */
  parentSpanId?: string;
}

/**
 * Tracing fields for workflow params
 *
 * Subset of TracingContext passed from Edge Functions to workflows.
 * The workflow creates new spanId for each operation.
 */
export interface WorkflowTracingParams {
  /** Business request correlation ID (UUID) */
  correlationId: string;

  /** User auth session ID (null if unauthenticated) */
  sessionId: string | null;

  /** W3C compatible trace ID (32 hex chars) */
  traceId: string;

  /** Parent span ID from the caller (Edge Function's span) */
  parentSpanId: string;
}

// ========================================
// Provider Interfaces
// ========================================

/**
 * DNS Provider Interface
 *
 * Abstraction for DNS operations (Cloudflare, Mock, Logging)
 */
export interface IDNSProvider {
  /**
   * List DNS zones for a domain
   */
  listZones(domain: string): Promise<DNSZone[]>;

  /**
   * List DNS records in a zone
   */
  listRecords(zoneId: string, filter?: DNSRecordFilter): Promise<DNSRecord[]>;

  /**
   * Create a new DNS record
   */
  createRecord(zoneId: string, params: CreateDNSRecordParams): Promise<DNSRecord>;

  /**
   * Delete a DNS record
   */
  deleteRecord(zoneId: string, recordId: string): Promise<void>;
}

/**
 * Email Provider Interface
 *
 * Abstraction for email operations (Resend, SMTP, Mock, Logging)
 */
export interface IEmailProvider {
  /**
   * Send an email
   */
  sendEmail(params: EmailParams): Promise<EmailResult>;

  /**
   * Verify email provider connection
   */
  verifyConnection?(): Promise<boolean>;
}
