components:
  schemas:
    # ==========================================================================
    # Base Event Types - Generic types for querying/displaying events
    # ==========================================================================

    StreamType:
      title: StreamType
      type: string
      description: Type of aggregate/stream that the event belongs to
      enum:
        - user
        - organization
        - organization_unit
        - invitation
        - program
        - platform_admin
        - impersonation
        - role
        - permission
        - contact
        - address
        - phone
        - access_grant

    DomainEvent:
      title: DomainEvent
      type: object
      description: |
        Generic domain event structure used for querying and displaying events.
        For type-safe handling of specific events, use the specific event interfaces
        (UserInvitedEvent, OrganizationBootstrapCompletedEvent, etc.)
      required:
        - id
        - stream_id
        - stream_type
        - stream_version
        - event_type
        - event_data
        - event_metadata
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique event identifier
        stream_id:
          type: string
          format: uuid
          description: The entity/aggregate this event belongs to
        stream_type:
          $ref: '#/components/schemas/StreamType'
        stream_version:
          type: integer
          minimum: 1
          description: Version number within this stream
        event_type:
          type: string
          pattern: '^[a-z_]+\.[a-z_]+$'
          description: Event type in format domain.action
          examples:
            - user.synced_from_auth
            - organization.bootstrap_initiated
        event_data:
          type: object
          description: The actual event payload
        event_metadata:
          $ref: '#/components/schemas/EventMetadata'
        created_at:
          type: string
          format: date-time
          description: When the event was created
        processed_at:
          type: string
          format: date-time
          description: When the event was successfully processed
          nullable: true
        processing_error:
          type: string
          description: Error message if processing failed
          nullable: true

    EventMetadata:
      title: EventMetadata
      type: object
      required:
        - user_id
        - reason
      properties:
        user_id:
          type: string
          format: uuid
          description: ID of the user who initiated this event
        organization_id:
          type: string
          format: uuid
          description: ID of the organization context for this event (multi-tenant isolation)
        reason:
          type: string
          minLength: 10
          maxLength: 500
          description: |
            Business justification for this action. This field captures the "WHY"
            behind every change and is REQUIRED for all events.
          examples:
            - "Patient showed allergic reaction to previous medication"
            - "Dosage adjustment per physician consultation on 2024-01-15"
            - "Regular intake from emergency department referral #12345"
        user_email:
          type: string
          format: email
          description: Email of the user who initiated this event
        user_name:
          type: string
          description: Name of the user who initiated this event
        correlation_id:
          type: string
          format: uuid
          description: ID to correlate related events across the system
        causation_id:
          type: string
          format: uuid
          description: ID of the event that caused this event
        ip_address:
          type: string
          format: ipv4
          description: IP address of the client
        user_agent:
          type: string
          description: User agent string of the client
        notes:
          type: string
          maxLength: 2000
          description: Additional context or notes

    Address:
      title: Address
      type: object
      properties:
        street:
          type: string
          maxLength: 200
        city:
          type: string
          maxLength: 100
        state:
          type: string
          maxLength: 2
          pattern: '^[A-Z]{2}$'
        zip_code:
          type: string
          pattern: '^\d{5}(-\d{4})?$'
        country:
          type: string
          default: USA
          maxLength: 100

    EmergencyContact:
      title: EmergencyContact
      type: object
      required:
        - name
        - relationship
        - phone
      properties:
        name:
          type: string
          maxLength: 200
        relationship:
          $ref: ../components/enums.yaml#/components/schemas/EmergencyContactRelationship
        phone:
          type: string
          pattern: '^\+?1?\d{10,14}$'
        alternate_phone:
          type: string
          pattern: '^\+?1?\d{10,14}$'
        email:
          type: string
          format: email

    Vitals:
      title: Vitals
      type: object
      properties:
        blood_pressure_systolic:
          type: integer
          minimum: 40
          maximum: 300
        blood_pressure_diastolic:
          type: integer
          minimum: 20
          maximum: 200
        heart_rate:
          type: integer
          minimum: 20
          maximum: 300
        temperature_fahrenheit:
          type: number
          minimum: 85.0
          maximum: 115.0
        respiratory_rate:
          type: integer
          minimum: 5
          maximum: 60
        oxygen_saturation:
          type: integer
          minimum: 50
          maximum: 100
        pain_scale:
          type: integer
          minimum: 0
          maximum: 10

    ValidationError:
      title: ValidationError
      type: object
      required:
        - field
        - message
        - code
      properties:
        field:
          type: string
          description: Field that failed validation
        message:
          type: string
          description: Human-readable error message
        code:
          allOf:
            - $ref: ../components/enums.yaml#/components/schemas/ValidationErrorCode
            - description: Machine-readable error code
