components:
  messages:
    UserInvited:
      name: user.invited
      title: User Invited
      summary: An invitation has been sent to a user to join an organization
      contentType: application/json
      payload:
        $ref: '#/components/schemas/UserInvitedEvent'

    InvitationRevoked:
      name: invitation.revoked
      title: Invitation Revoked
      summary: A pending invitation has been revoked (typically during workflow compensation)
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationRevokedEvent'

    InvitationAccepted:
      name: invitation.accepted
      title: Invitation Accepted
      summary: A user has accepted an invitation and joined the organization
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationAcceptedEvent'

    InvitationExpired:
      name: invitation.expired
      title: Invitation Expired
      summary: An invitation has expired without being accepted
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationExpiredEvent'

  schemas:
    UserInvitedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Organization UUID (invitation belongs to organization aggregate)
        stream_type:
          type: string
          const: organization
          description: Events emitted on organization aggregate
        event_type:
          type: string
          const: user.invited
        event_data:
          $ref: '#/components/schemas/UserInvitedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    UserInvitedData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - first_name
        - last_name
        - roles
        - token
        - expires_at
      properties:
        invitation_id:
          type: string
          format: uuid
          description: Unique identifier for this invitation
        org_id:
          type: string
          format: uuid
          description: Organization the user is being invited to
        email:
          type: string
          format: email
          description: Email address of the invited user
          examples:
            - "admin@provider.com"
            - "clinician@healthcare.org"
        first_name:
          type: string
          maxLength: 100
          description: First name of the invited user
        last_name:
          type: string
          maxLength: 100
          description: Last name of the invited user
        roles:
          type: array
          minItems: 1
          description: |
            Roles to assign when invitation is accepted. Supports both canonical
            system roles and custom organization-defined roles. Each role includes
            a denormalized name snapshot for display purposes.
          items:
            type: object
            required:
              - role_id
            properties:
              role_id:
                type: string
                format: uuid
                description: UUID of the role to assign
              role_name:
                type: string
                maxLength: 100
                description: Denormalized role name snapshot for display (e.g., "Program Manager - Aspen")
          examples:
            - - role_id: "11111111-1111-1111-1111-111111111111"
                role_name: "super_admin"
            - - role_id: "550e8400-e29b-41d4-a716-446655440001"
                role_name: "Program Manager - Aspen"
              - role_id: "550e8400-e29b-41d4-a716-446655440002"
                role_name: "Clinician"
        token:
          type: string
          description: Cryptographically secure invitation token (256 bits, base64url encoded)
          examples:
            - "xK9m2nP4qR7sT1vW3xY5zA8bC0dE2fG4hI6jK8lM0nO"
        expires_at:
          type: string
          format: date-time
          description: When the invitation expires (default 7 days from creation)
          examples:
            - "2025-11-25T13:54:00.000Z"
        access_start_date:
          type: string
          format: date
          nullable: true
          description: First date the user can access the org after accepting (NULL = immediate)
          examples:
            - "2025-01-15"
            - null
        access_expiration_date:
          type: string
          format: date
          nullable: true
          description: Date the user's access will expire (NULL = no expiration)
          examples:
            - "2025-12-31"
            - null
        notification_preferences:
          $ref: '#/components/schemas/NotificationPreferences'
          description: Initial notification preferences for the user

    NotificationPreferences:
      type: object
      description: User notification preferences (per-org)
      properties:
        email:
          type: boolean
          default: true
          description: Whether to send email notifications
        sms:
          type: object
          properties:
            enabled:
              type: boolean
              default: false
              description: Whether to send SMS notifications
            phone_id:
              type: string
              format: uuid
              nullable: true
              description: UUID of the phone to use for SMS (from user_phones or user_org_phone_overrides)
        in_app:
          type: boolean
          default: false
          description: Whether to send in-app notifications (future feature)

    InvitationRevokedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Invitation UUID being revoked
        stream_type:
          type: string
          const: invitation
          description: Events emitted on invitation aggregate
        event_type:
          type: string
          const: invitation.revoked
        event_data:
          $ref: '#/components/schemas/InvitationRevokedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationRevokedData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - revoked_at
        - reason
      properties:
        invitation_id:
          type: string
          format: uuid
          description: Invitation being revoked
        org_id:
          type: string
          format: uuid
          description: Organization the invitation belonged to
        email:
          type: string
          format: email
          description: Email of the user whose invitation was revoked
        revoked_at:
          type: string
          format: date-time
          description: Timestamp when the invitation was revoked
        reason:
          type: string
          enum: [workflow_failure, manual_revocation, organization_deactivated]
          description: |
            Reason for revocation:
            - workflow_failure: Saga compensation during failed organization bootstrap
            - manual_revocation: Administrator manually revoked the invitation
            - organization_deactivated: Organization was deactivated, invalidating invitations

    InvitationAcceptedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Invitation UUID that was accepted
        stream_type:
          type: string
          const: invitation
        event_type:
          type: string
          const: invitation.accepted
        event_data:
          $ref: '#/components/schemas/InvitationAcceptedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationAcceptedData:
      type: object
      required:
        - invitation_id
        - org_id
        - user_id
        - email
        - roles
        - accepted_at
      properties:
        invitation_id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          description: User ID created in auth system
        email:
          type: string
          format: email
        roles:
          type: array
          minItems: 1
          description: |
            Snapshot of roles from the invitation that were promised to the user.
            The actual role grants are emitted as separate user.role.assigned events.
          items:
            type: object
            required:
              - role_id
            properties:
              role_id:
                type: string
                format: uuid
                description: UUID of the role that was assigned
              role_name:
                type: string
                maxLength: 100
                description: Denormalized role name snapshot
        accepted_at:
          type: string
          format: date-time
        access_start_date:
          type: string
          format: date
          nullable: true
          description: First date the user can access the org (copied from invitation)
        access_expiration_date:
          type: string
          format: date
          nullable: true
          description: Date the user's access will expire (copied from invitation)
        notification_preferences:
          $ref: '#/components/schemas/NotificationPreferences'
          description: Notification preferences (copied from invitation to user_org_access)

    InvitationExpiredEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
        stream_type:
          type: string
          const: invitation
        event_type:
          type: string
          const: invitation.expired
        event_data:
          $ref: '#/components/schemas/InvitationExpiredData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationExpiredData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - expired_at
        - original_expires_at
      properties:
        invitation_id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        expired_at:
          type: string
          format: date-time
          description: When the system processed the expiration
        original_expires_at:
          type: string
          format: date-time
          description: Original expiration date from the invitation
