components:
  messages:
    UserInvited:
      name: invitation.user_invited
      title: User Invited
      summary: An invitation has been sent to a user to join an organization
      contentType: application/json
      payload:
        $ref: '#/components/schemas/UserInvitedEvent'

    InvitationRevoked:
      name: invitation.revoked
      title: Invitation Revoked
      summary: A pending invitation has been revoked (typically during workflow compensation)
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationRevokedEvent'

    InvitationAccepted:
      name: invitation.accepted
      title: Invitation Accepted
      summary: A user has accepted an invitation and joined the organization
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationAcceptedEvent'

    InvitationExpired:
      name: invitation.expired
      title: Invitation Expired
      summary: An invitation has expired without being accepted
      contentType: application/json
      payload:
        $ref: '#/components/schemas/InvitationExpiredEvent'

  schemas:
    UserInvitedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Organization UUID (invitation belongs to organization aggregate)
        stream_type:
          type: string
          enum: [organization]
          description: Events emitted on organization aggregate
        event_type:
          type: string
          enum: [UserInvited]
        event_data:
          $ref: '#/components/schemas/UserInvitedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    UserInvitedData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - first_name
        - last_name
        - role
        - token
        - expires_at
      properties:
        invitation_id:
          type: string
          format: uuid
          description: Unique identifier for this invitation
        org_id:
          type: string
          format: uuid
          description: Organization the user is being invited to
        email:
          type: string
          format: email
          description: Email address of the invited user
          examples:
            - "admin@provider.com"
            - "clinician@healthcare.org"
        first_name:
          type: string
          maxLength: 100
          description: First name of the invited user
        last_name:
          type: string
          maxLength: 100
          description: Last name of the invited user
        role:
          type: string
          enum: [provider_admin, partner_admin, clinician, viewer]
          description: |
            Role to assign when invitation is accepted:
            - provider_admin: Full administrative access for provider organizations
            - partner_admin: Full administrative access for partner organizations
            - clinician: Clinical staff with medication management access
            - viewer: Read-only access
        token:
          type: string
          description: Cryptographically secure invitation token (256 bits, base64url encoded)
          examples:
            - "xK9m2nP4qR7sT1vW3xY5zA8bC0dE2fG4hI6jK8lM0nO"
        expires_at:
          type: string
          format: date-time
          description: When the invitation expires (default 7 days from creation)
          examples:
            - "2025-11-25T13:54:00.000Z"

    InvitationRevokedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Invitation UUID being revoked
        stream_type:
          type: string
          enum: [invitation]
          description: Events emitted on invitation aggregate
        event_type:
          type: string
          enum: [InvitationRevoked]
        event_data:
          $ref: '#/components/schemas/InvitationRevokedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationRevokedData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - revoked_at
        - reason
      properties:
        invitation_id:
          type: string
          format: uuid
          description: Invitation being revoked
        org_id:
          type: string
          format: uuid
          description: Organization the invitation belonged to
        email:
          type: string
          format: email
          description: Email of the user whose invitation was revoked
        revoked_at:
          type: string
          format: date-time
          description: Timestamp when the invitation was revoked
        reason:
          type: string
          enum: [workflow_failure, manual_revocation, organization_deactivated]
          description: |
            Reason for revocation:
            - workflow_failure: Saga compensation during failed organization bootstrap
            - manual_revocation: Administrator manually revoked the invitation
            - organization_deactivated: Organization was deactivated, invalidating invitations

    InvitationAcceptedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Invitation UUID that was accepted
        stream_type:
          type: string
          enum: [invitation]
        event_type:
          type: string
          enum: [InvitationAccepted]
        event_data:
          $ref: '#/components/schemas/InvitationAcceptedData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationAcceptedData:
      type: object
      required:
        - invitation_id
        - org_id
        - user_id
        - email
        - role
        - accepted_at
      properties:
        invitation_id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          description: User ID created in auth system
        email:
          type: string
          format: email
        role:
          type: string
          enum: [provider_admin, partner_admin, clinician, viewer]
        accepted_at:
          type: string
          format: date-time

    InvitationExpiredEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
        stream_type:
          type: string
          enum: [invitation]
        event_type:
          type: string
          enum: [InvitationExpired]
        event_data:
          $ref: '#/components/schemas/InvitationExpiredData'
        event_metadata:
          $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'

    InvitationExpiredData:
      type: object
      required:
        - invitation_id
        - org_id
        - email
        - expired_at
        - original_expires_at
      properties:
        invitation_id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        expired_at:
          type: string
          format: date-time
          description: When the system processed the expiration
        original_expires_at:
          type: string
          format: date-time
          description: Original expiration date from the invitation
