components:
  messages:
    PermissionDefined:
      name: permission.defined
      title: Permission Defined
      summary: A new permission has been created in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/PermissionDefinedEvent'

    RoleCreated:
      name: role.created
      title: Role Created
      summary: A new role has been created
      contentType: application/json
      payload:
        $ref: '#/components/schemas/RoleCreatedEvent'

    RolePermissionGranted:
      name: role.permission.granted
      title: Role Permission Granted
      summary: A permission has been granted to a role
      contentType: application/json
      payload:
        $ref: '#/components/schemas/RolePermissionGrantedEvent'

    RolePermissionRevoked:
      name: role.permission.revoked
      title: Role Permission Revoked
      summary: A permission has been revoked from a role
      contentType: application/json
      payload:
        $ref: '#/components/schemas/RolePermissionRevokedEvent'

    UserRoleAssigned:
      name: user.role.assigned
      title: User Role Assigned
      summary: A role has been assigned to a user
      contentType: application/json
      payload:
        $ref: '#/components/schemas/UserRoleAssignedEvent'

    UserRoleRevoked:
      name: user.role.revoked
      title: User Role Revoked
      summary: A role has been revoked from a user
      contentType: application/json
      payload:
        $ref: '#/components/schemas/UserRoleRevokedEvent'

    AccessGrantCreated:
      name: access_grant.created
      title: Access Grant Created
      summary: A cross-tenant access grant has been created
      contentType: application/json
      payload:
        $ref: '#/components/schemas/AccessGrantCreatedEvent'

    AccessGrantRevoked:
      name: access_grant.revoked
      title: Access Grant Revoked
      summary: A cross-tenant access grant has been revoked
      contentType: application/json
      payload:
        $ref: '#/components/schemas/AccessGrantRevokedEvent'

  schemas:
    PermissionDefinedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Permission UUID
        stream_type:
          type: string
          const: permission
        event_type:
          type: string
          const: permission.defined
        event_data:
          type: object
          required:
            - applet
            - action
            - description
            - scope_type
            - requires_mfa
          properties:
            applet:
              type: string
              description: Functional module (medication, provider, client, etc.)
              examples:
                - medication
                - provider
                - client
                - user
            action:
              type: string
              description: Specific capability within the applet
              examples:
                - create
                - view
                - update
                - delete
                - approve
                - impersonate
            description:
              type: string
              description: Human-readable explanation of the permission
              examples:
                - Create new medication prescriptions
                - View client records
                - Impersonate users for support operations
            scope_type:
              type: string
              enum:
                - global
                - org
                - facility
                - program
                - client
              description: Hierarchical scope level for this permission
            requires_mfa:
              type: boolean
              description: Whether MFA is required to use this permission
              default: false
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Adding new permission for medication approval workflow
                    - Creating permission for cross-tenant access grants
                    - Defining impersonation permission for Super Admin support

    RoleCreatedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Role UUID
        stream_type:
          type: string
          const: role
        event_type:
          type: string
          const: role.created
        event_data:
          type: object
          required:
            - name
            - description
          properties:
            name:
              type: string
              description: Role identifier
              examples:
                - super_admin
                - provider_admin
                - facility_admin
                - clinician
            description:
              type: string
              description: Human-readable role description
              examples:
                - Platform-wide administrator with all permissions
                - Organization administrator with org-scoped permissions
            zitadel_org_id:
              type: string
              nullable: true
              description: Zitadel organization ID (NULL for super_admin)
            org_hierarchy_scope:
              type: string
              nullable: true
              description: ltree path for hierarchical scoping (NULL for super_admin)
              examples:
                - org_acme_healthcare_001
                - org_acme_healthcare_001.facility_456
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Creating super admin role for platform administration
                    - Creating provider admin role for organization-level management
                    - Adding new role for facility-scoped access

    RolePermissionGrantedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Role UUID
        stream_type:
          type: string
          const: role
        event_type:
          type: string
          const: role.permission.granted
        event_data:
          type: object
          required:
            - permission_id
            - permission_name
          properties:
            permission_id:
              type: string
              format: uuid
              description: UUID of the permission being granted
            permission_name:
              type: string
              description: Full permission identifier (for logging)
              pattern: '^[a-z_]+\.[a-z_]+$'
              examples:
                - medication.create
                - provider.impersonate
                - client.view
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Granting medication creation permission to provider_admin role
                    - Adding impersonation permission to super_admin role
                    - Granting view permission to read-only auditor role

    RolePermissionRevokedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Role UUID
        stream_type:
          type: string
          const: role
        event_type:
          type: string
          const: role.permission.revoked
        event_data:
          type: object
          required:
            - permission_id
            - permission_name
            - revocation_reason
          properties:
            permission_id:
              type: string
              format: uuid
            permission_name:
              type: string
              pattern: '^[a-z_]+\.[a-z_]+$'
            revocation_reason:
              type: string
              description: Explanation for permission removal
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Removing impersonation permission from provider_admin due to security policy change
                    - Revoking delete permission from role per compliance requirement

    UserRoleAssignedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: User UUID
        stream_type:
          type: string
          const: user
        event_type:
          type: string
          const: user.role.assigned
        event_data:
          type: object
          required:
            - role_id
            - role_name
            - org_id
            - scope_path
            - assigned_by
          properties:
            role_id:
              type: string
              format: uuid
              description: UUID of the role being assigned
            role_name:
              type: string
              description: Role identifier for logging
              examples:
                - super_admin
                - provider_admin
            org_id:
              type: string
              description: Organization ID ('*' for super_admin, specific org for others)
              examples:
                - '*'
                - acme_healthcare_001
            scope_path:
              type: string
              description: ltree hierarchy path ('*' for global, specific path for scoped)
              examples:
                - '*'
                - org_acme_healthcare_001
                - org_acme_healthcare_001.facility_456
            assigned_by:
              type: string
              format: uuid
              description: User who performed the assignment
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Granting platform-wide administrative access to new A4C support engineer
                    - Granting provider administrator access to manage Acme Healthcare organization
                    - Assigning facility admin role for facility-level management

    UserRoleRevokedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: User UUID
        stream_type:
          type: string
          const: user
        event_type:
          type: string
          const: user.role.revoked
        event_data:
          type: object
          required:
            - role_id
            - role_name
            - org_id
            - revoked_by
          properties:
            role_id:
              type: string
              format: uuid
            role_name:
              type: string
            org_id:
              type: string
            revoked_by:
              type: string
              format: uuid
              description: User who performed the revocation
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - User terminated employment, revoking all access
                    - Downgrading permissions per security audit recommendation
                    - Temporary role assignment expired

    AccessGrantCreatedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Access grant UUID
        stream_type:
          type: string
          const: access_grant
        event_type:
          type: string
          const: access_grant.created
        event_data:
          type: object
          required:
            - consultant_org_id
            - provider_org_id
            - scope
            - authorization_type
          properties:
            consultant_org_id:
              type: string
              description: Provider Partner organization ID
            consultant_user_id:
              type: string
              format: uuid
              nullable: true
              description: Specific user (NULL for org-wide grant)
            provider_org_id:
              type: string
              description: Target Provider organization ID
            scope:
              type: string
              enum:
                - full_org
                - facility
                - client
              description: Access scope level
            scope_id:
              type: string
              format: uuid
              nullable: true
              description: Specific resource ID if scoped
            authorization_type:
              type: string
              enum:
                - court_order
                - parental_consent
                - var_contract
                - social_services
              description: Legal basis for cross-tenant access
            legal_reference:
              type: string
              nullable: true
              description: Court order number, consent form ID, contract reference
              examples:
                - Court Order #2024-1234
                - Parental Consent Form #PC-5678
                - VAR Contract #VAR-2024-001
            expires_at:
              type: string
              format: date-time
              nullable: true
              description: Expiration timestamp for time-limited access
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Granting court access per order #2024-1234 for case review
                    - Creating VAR access grant for partner dashboard analytics
                    - Granting parental access to minor client records per consent

    AccessGrantRevokedEvent:
      type: object
      required:
        - stream_id
        - stream_type
        - event_type
        - event_data
        - event_metadata
      properties:
        stream_id:
          type: string
          format: uuid
          description: Access grant UUID
        stream_type:
          type: string
          const: access_grant
        event_type:
          type: string
          const: access_grant.revoked
        event_data:
          type: object
          required:
            - grant_id
            - revoked_by
            - revocation_reason
          properties:
            grant_id:
              type: string
              format: uuid
              description: UUID of the grant being revoked
            revoked_by:
              type: string
              format: uuid
              description: User who revoked the grant
            revocation_reason:
              type: string
              description: Explanation for revocation
              examples:
                - Court case closed, access no longer required
                - VAR contract terminated
                - Parental custody changed, consent withdrawn
        event_metadata:
          allOf:
            - $ref: '../components/schemas.yaml#/components/schemas/EventMetadata'
            - properties:
                reason:
                  examples:
                    - Revoking court access after case closure per provider admin request
                    - Terminating VAR access due to contract expiration
                    - Withdrawing parental access per custody order
