#!/usr/bin/env node

/**
 * Schema Sync Script
 *
 * Syncs TypeScript event type definitions from the infrastructure directory
 * to the frontend at build time (monorepo structure).
 *
 * This ensures the frontend always uses the latest event contracts defined
 * in the infrastructure/supabase/contracts/types directory (source of truth).
 */

const fs = require('fs');
const path = require('path');

// Configuration
// Updated for monorepo structure - infrastructure is now a sibling directory in the monorepo
const MONOREPO_ROOT = path.resolve(__dirname, '../../');
const INFRASTRUCTURE_DIR = path.join(MONOREPO_ROOT, 'infrastructure');
const SOURCE_DIR = path.join(INFRASTRUCTURE_DIR, 'supabase/contracts/types');
const TARGET_DIR = path.resolve(__dirname, '../src/types/generated');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function error(message) {
  log(`❌ ${message}`, 'red');
}

function success(message) {
  log(`✅ ${message}`, 'green');
}

function info(message) {
  log(`ℹ️  ${message}`, 'blue');
}

function warning(message) {
  log(`⚠️  ${message}`, 'yellow');
}

/**
 * Check if Infrastructure directory exists (monorepo structure)
 */
function checkInfrastructureRepo() {
  if (!fs.existsSync(INFRASTRUCTURE_DIR)) {
    error('Infrastructure directory not found!');
    error(`Expected location: ${INFRASTRUCTURE_DIR}`);
    error('This is a monorepo - infrastructure should be at the repository root.');
    process.exit(1);
  }

  if (!fs.existsSync(SOURCE_DIR)) {
    error('Event types directory not found in Infrastructure!');
    error(`Expected location: ${SOURCE_DIR}`);
    error('Please ensure infrastructure/supabase/contracts/types directory exists.');
    process.exit(1);
  }

  success('Infrastructure directory found (monorepo structure)');
}

/**
 * Create target directory if it doesn't exist
 */
function ensureTargetDirectory() {
  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
    success(`Created target directory: ${TARGET_DIR}`);
  }
}

/**
 * Add header comment to generated files
 */
function addGeneratedHeader(content, sourceFile) {
  const header = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is automatically generated from the infrastructure directory (monorepo).
 * Source: infrastructure/supabase/contracts/types/${sourceFile}
 *
 * To update these types:
 * 1. Modify the source files in infrastructure/supabase/contracts/types
 * 2. Run: npm run sync-schemas
 *
 * Last synced: ${new Date().toISOString()}
 */

`;
  return header + content;
}

/**
 * Copy and process TypeScript files
 */
function syncSchemas() {
  try {
    // Get all TypeScript files from source directory
    const files = fs.readdirSync(SOURCE_DIR).filter(file => file.endsWith('.ts'));

    if (files.length === 0) {
      warning('No TypeScript files found in source directory');
      return;
    }

    let syncedCount = 0;

    files.forEach(file => {
      const sourcePath = path.join(SOURCE_DIR, file);
      const targetPath = path.join(TARGET_DIR, file);

      // Read source file
      const content = fs.readFileSync(sourcePath, 'utf8');

      // Add header and write to target
      const processedContent = addGeneratedHeader(content, file);
      fs.writeFileSync(targetPath, processedContent, 'utf8');

      info(`Synced: ${file}`);
      syncedCount++;
    });

    success(`Synced ${syncedCount} file(s) successfully!`);
  } catch (err) {
    error(`Failed to sync schemas: ${err.message}`);
    process.exit(1);
  }
}

/**
 * Create index.ts for convenient imports
 */
function createIndexFile() {
  const indexPath = path.join(TARGET_DIR, 'index.ts');
  const content = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Re-exports all event types from generated files.
 * Last generated: ${new Date().toISOString()}
 */

export * from './events';
`;

  fs.writeFileSync(indexPath, content, 'utf8');
  info('Created index.ts for convenient imports');
}

/**
 * Main execution
 */
function main() {
  log('\n🔄 Starting schema sync...', 'blue');
  log('─'.repeat(50), 'blue');

  checkInfrastructureRepo();
  ensureTargetDirectory();
  syncSchemas();
  createIndexFile();

  log('─'.repeat(50), 'green');
  success('Schema sync completed!\n');
}

// Run the script
main();
