#!/usr/bin/env node

/**
 * Schema Sync Script (workflows)
 *
 * Syncs the generated event types from the canonical AsyncAPI codegen output
 * to the workflows source tree. The frontend uses an analogous script.
 *
 * Source of truth:
 *   infrastructure/supabase/contracts/types/generated-events.ts
 * Target:
 *   workflows/src/shared/types/generated/events.ts
 *
 * The source file is auto-generated by:
 *   cd infrastructure/supabase/contracts && npm run generate:types
 *
 * After regenerating types in contracts/, run this script to propagate the
 * change into workflows/.
 */

const fs = require('fs');
const path = require('path');

const MONOREPO_ROOT = path.resolve(__dirname, '../../');
const SOURCE_FILE = path.join(
  MONOREPO_ROOT,
  'infrastructure/supabase/contracts/types/generated-events.ts'
);
const TARGET_DIR = path.resolve(__dirname, '../src/shared/types/generated');
const TARGET_FILE = path.join(TARGET_DIR, 'events.ts');

function header() {
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Synced from infrastructure/supabase/contracts/types/generated-events.ts
 * (which is itself generated from the AsyncAPI spec).
 *
 * To update:
 * 1. Edit AsyncAPI source under infrastructure/supabase/contracts/asyncapi/
 *    (or the curated types in infrastructure/supabase/contracts/types/events.ts).
 * 2. cd infrastructure/supabase/contracts && npm run generate:types
 * 3. cd workflows && npm run sync-schemas
 *
 * Last synced: ${new Date().toISOString()}
 */

`;
}

function main() {
  if (!fs.existsSync(SOURCE_FILE)) {
    console.error(`Source not found: ${SOURCE_FILE}`);
    console.error(
      'Run `cd infrastructure/supabase/contracts && npm run generate:types` first.'
    );
    process.exit(1);
  }

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }

  const sourceContent = fs.readFileSync(SOURCE_FILE, 'utf8');
  const stripped = sourceContent.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');
  fs.writeFileSync(TARGET_FILE, header() + stripped, 'utf8');
  console.log(`Synced -> ${path.relative(MONOREPO_ROOT, TARGET_FILE)}`);
}

main();
