CREATE OR REPLACE FUNCTION public.handle_client_registered(p_event record)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
DECLARE
    v_user_id uuid;
BEGIN
    v_user_id := COALESCE(
        (p_event.event_metadata->>'user_id')::uuid,
        '00000000-0000-0000-0000-000000000000'::uuid
    );

    INSERT INTO clients_projection (
        id,
        organization_id,
        organization_unit_id,
        status,
        data_source,
        -- Demographics
        first_name,
        last_name,
        middle_name,
        preferred_name,
        date_of_birth,
        gender,
        gender_identity,
        pronouns,
        race,
        ethnicity,
        primary_language,
        secondary_language,
        interpreter_needed,
        marital_status,
        citizenship_status,
        photo_url,
        mrn,
        external_id,
        drivers_license,
        -- Referral
        referral_source_type,
        referral_organization,
        referral_date,
        reason_for_referral,
        -- Admission
        admission_date,
        admission_type,
        level_of_care,
        expected_length_of_stay,
        initial_risk_level,
        discharge_plan_status,
        placement_arrangement,
        -- Insurance IDs
        medicaid_id,
        medicare_id,
        -- Clinical
        primary_diagnosis,
        secondary_diagnoses,
        dsm5_diagnoses,
        presenting_problem,
        suicide_risk_status,
        violence_risk_status,
        trauma_history_indicator,
        substance_use_history,
        developmental_history,
        previous_treatment_history,
        -- Medical
        allergies,
        medical_conditions,
        immunization_status,
        dietary_restrictions,
        special_medical_needs,
        -- Legal
        legal_custody_status,
        court_ordered_placement,
        financial_guarantor_type,
        court_case_number,
        state_agency,
        legal_status,
        mandated_reporting_status,
        protective_services_involvement,
        safety_plan_required,
        -- Education
        education_status,
        grade_level,
        iep_status,
        -- Custom fields
        custom_fields,
        -- Audit
        created_at,
        updated_at,
        created_by,
        updated_by,
        last_event_id
    ) VALUES (
        p_event.stream_id,
        (p_event.event_data->>'organization_id')::uuid,
        (p_event.event_data->>'organization_unit_id')::uuid,
        COALESCE(p_event.event_data->>'status', 'active'),
        COALESCE(p_event.event_data->>'data_source', 'manual'),
        -- Demographics
        p_event.event_data->>'first_name',
        p_event.event_data->>'last_name',
        p_event.event_data->>'middle_name',
        p_event.event_data->>'preferred_name',
        (p_event.event_data->>'date_of_birth')::date,
        p_event.event_data->>'gender',
        p_event.event_data->>'gender_identity',
        p_event.event_data->>'pronouns',
        CASE WHEN p_event.event_data ? 'race' THEN
            ARRAY(SELECT jsonb_array_elements_text(p_event.event_data->'race'))
        ELSE NULL END,
        p_event.event_data->>'ethnicity',
        p_event.event_data->>'primary_language',
        p_event.event_data->>'secondary_language',
        (p_event.event_data->>'interpreter_needed')::boolean,
        p_event.event_data->>'marital_status',
        p_event.event_data->>'citizenship_status',
        p_event.event_data->>'photo_url',
        p_event.event_data->>'mrn',
        p_event.event_data->>'external_id',
        p_event.event_data->>'drivers_license',
        -- Referral
        p_event.event_data->>'referral_source_type',
        p_event.event_data->>'referral_organization',
        (p_event.event_data->>'referral_date')::date,
        p_event.event_data->>'reason_for_referral',
        -- Admission
        (p_event.event_data->>'admission_date')::date,
        p_event.event_data->>'admission_type',
        p_event.event_data->>'level_of_care',
        (p_event.event_data->>'expected_length_of_stay')::integer,
        p_event.event_data->>'initial_risk_level',
        p_event.event_data->>'discharge_plan_status',
        p_event.event_data->>'placement_arrangement',
        -- Insurance IDs
        p_event.event_data->>'medicaid_id',
        p_event.event_data->>'medicare_id',
        -- Clinical
        CASE WHEN p_event.event_data ? 'primary_diagnosis' THEN p_event.event_data->'primary_diagnosis' ELSE NULL END,
        CASE WHEN p_event.event_data ? 'secondary_diagnoses' THEN p_event.event_data->'secondary_diagnoses' ELSE NULL END,
        CASE WHEN p_event.event_data ? 'dsm5_diagnoses' THEN p_event.event_data->'dsm5_diagnoses' ELSE NULL END,
        p_event.event_data->>'presenting_problem',
        p_event.event_data->>'suicide_risk_status',
        p_event.event_data->>'violence_risk_status',
        (p_event.event_data->>'trauma_history_indicator')::boolean,
        p_event.event_data->>'substance_use_history',
        p_event.event_data->>'developmental_history',
        p_event.event_data->>'previous_treatment_history',
        -- Medical
        COALESCE(p_event.event_data->'allergies', '{"nka": true, "items": []}'::jsonb),
        COALESCE(p_event.event_data->'medical_conditions', '{"nkmc": true, "items": []}'::jsonb),
        p_event.event_data->>'immunization_status',
        p_event.event_data->>'dietary_restrictions',
        p_event.event_data->>'special_medical_needs',
        -- Legal
        p_event.event_data->>'legal_custody_status',
        (p_event.event_data->>'court_ordered_placement')::boolean,
        p_event.event_data->>'financial_guarantor_type',
        p_event.event_data->>'court_case_number',
        p_event.event_data->>'state_agency',
        p_event.event_data->>'legal_status',
        (p_event.event_data->>'mandated_reporting_status')::boolean,
        (p_event.event_data->>'protective_services_involvement')::boolean,
        (p_event.event_data->>'safety_plan_required')::boolean,
        -- Education
        p_event.event_data->>'education_status',
        p_event.event_data->>'grade_level',
        (p_event.event_data->>'iep_status')::boolean,
        -- Custom fields
        COALESCE(p_event.event_data->'custom_fields', '{}'::jsonb),
        -- Audit
        p_event.created_at,
        p_event.created_at,
        v_user_id,
        v_user_id,
        p_event.id
    )
    ON CONFLICT (id) DO UPDATE SET
        organization_unit_id = EXCLUDED.organization_unit_id,
        status = EXCLUDED.status,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        middle_name = EXCLUDED.middle_name,
        preferred_name = EXCLUDED.preferred_name,
        date_of_birth = EXCLUDED.date_of_birth,
        gender = EXCLUDED.gender,
        gender_identity = EXCLUDED.gender_identity,
        pronouns = EXCLUDED.pronouns,
        race = EXCLUDED.race,
        ethnicity = EXCLUDED.ethnicity,
        primary_language = EXCLUDED.primary_language,
        secondary_language = EXCLUDED.secondary_language,
        interpreter_needed = EXCLUDED.interpreter_needed,
        marital_status = EXCLUDED.marital_status,
        citizenship_status = EXCLUDED.citizenship_status,
        photo_url = EXCLUDED.photo_url,
        mrn = EXCLUDED.mrn,
        external_id = EXCLUDED.external_id,
        drivers_license = EXCLUDED.drivers_license,
        referral_source_type = EXCLUDED.referral_source_type,
        referral_organization = EXCLUDED.referral_organization,
        referral_date = EXCLUDED.referral_date,
        reason_for_referral = EXCLUDED.reason_for_referral,
        admission_date = EXCLUDED.admission_date,
        admission_type = EXCLUDED.admission_type,
        level_of_care = EXCLUDED.level_of_care,
        expected_length_of_stay = EXCLUDED.expected_length_of_stay,
        initial_risk_level = EXCLUDED.initial_risk_level,
        discharge_plan_status = EXCLUDED.discharge_plan_status,
        placement_arrangement = EXCLUDED.placement_arrangement,
        medicaid_id = EXCLUDED.medicaid_id,
        medicare_id = EXCLUDED.medicare_id,
        primary_diagnosis = EXCLUDED.primary_diagnosis,
        secondary_diagnoses = EXCLUDED.secondary_diagnoses,
        dsm5_diagnoses = EXCLUDED.dsm5_diagnoses,
        presenting_problem = EXCLUDED.presenting_problem,
        suicide_risk_status = EXCLUDED.suicide_risk_status,
        violence_risk_status = EXCLUDED.violence_risk_status,
        trauma_history_indicator = EXCLUDED.trauma_history_indicator,
        substance_use_history = EXCLUDED.substance_use_history,
        developmental_history = EXCLUDED.developmental_history,
        previous_treatment_history = EXCLUDED.previous_treatment_history,
        allergies = EXCLUDED.allergies,
        medical_conditions = EXCLUDED.medical_conditions,
        immunization_status = EXCLUDED.immunization_status,
        dietary_restrictions = EXCLUDED.dietary_restrictions,
        special_medical_needs = EXCLUDED.special_medical_needs,
        legal_custody_status = EXCLUDED.legal_custody_status,
        court_ordered_placement = EXCLUDED.court_ordered_placement,
        financial_guarantor_type = EXCLUDED.financial_guarantor_type,
        court_case_number = EXCLUDED.court_case_number,
        state_agency = EXCLUDED.state_agency,
        legal_status = EXCLUDED.legal_status,
        mandated_reporting_status = EXCLUDED.mandated_reporting_status,
        protective_services_involvement = EXCLUDED.protective_services_involvement,
        safety_plan_required = EXCLUDED.safety_plan_required,
        education_status = EXCLUDED.education_status,
        grade_level = EXCLUDED.grade_level,
        iep_status = EXCLUDED.iep_status,
        custom_fields = EXCLUDED.custom_fields,
        updated_at = EXCLUDED.updated_at,
        updated_by = EXCLUDED.updated_by,
        last_event_id = EXCLUDED.last_event_id;
END;
$function$;
