# Temporal Secrets Template
# Copy this file to secrets.yaml and fill in actual values
# secrets.yaml should be encrypted with git-crypt

apiVersion: v1
kind: Secret
metadata:
  name: temporal-credentials
  namespace: temporal
type: Opaque
stringData:
  # Cloudflare API credentials
  CLOUDFLARE_API_TOKEN: "REPLACE_WITH_ACTUAL_TOKEN"
  CLOUDFLARE_ZONE_ID: "REPLACE_WITH_ACTUAL_ZONE_ID"

  # Zitadel service account
  ZITADEL_API_URL: "https://analytics4change-zdswvg.us1.zitadel.cloud"
  ZITADEL_SERVICE_USER_ID: "REPLACE_WITH_SERVICE_USER_ID"
  ZITADEL_SERVICE_USER_SECRET: "REPLACE_WITH_SERVICE_USER_SECRET"

  # Supabase connection
  SUPABASE_URL: "https://tmrjlswbsxmbglmaclxu.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: "REPLACE_WITH_SERVICE_ROLE_KEY"
