# Temporal Helm Chart Values - PostgreSQL Configuration
# Based on official values.postgresql.yaml from temporalio/helm-charts
# PostgreSQL deployed separately (see postgresql.yaml)
# Schemas initialized via schema-init.yaml job

server:
  replicaCount: 1

  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "temporal-postgresql.temporal.svc.cluster.local"
          port: 5432
          database: "temporal"
          user: "postgres"
          password: "temporal-dev-password"
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "temporal-postgresql.temporal.svc.cluster.local"
          port: 5432
          database: "temporal_visibility"
          user: "postgres"
          password: "temporal-dev-password"
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Disable built-in datastores
cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false  # We deploy our own PostgreSQL

elasticsearch:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

# Web UI
web:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Schema setup - disabled because we initialize schemas manually
schema:
  createDatabase:
    enabled: false
  setup:
    enabled: false
  update:
    enabled: false

# Labels
commonLabels:
  app: temporal
  managed-by: helm
  project: a4c
  environment: development
